### ISSUE TITLE
스크립트-자동갱신에서 스케줄 날짜를 매일로 하는것이 맞을까요?

### ISSUE THREAD

**Issue by hohomin320** [mschadev/synology-gitlab-ssl#1]
![image](https://user-images.githubusercontent.com/19955912/114843119-738bac00-9e14-11eb-9f87-aec5b11ddd25.png)

**Comment by mschadev** [comment]
네 그렇게 하셔도 됩니다.
스크립트가 실행될 때 시놀로지에 등록된 인증서와 Gitlab에 쓴 인증서의 유효기간을 비교하므로 편하신대로 하시면 됩니다.
